image: node:14.10.1-apline

build:
  stage: build
  before_script:
    - apk add mvn
    - npm install -g create-react-app
  script:
    - mvn clean install
  only:
    - master

  artifacts:
    paths:
      - ./target/sparker-0.0.1-SNAPSHOT.jar
