image: cschockaert/docker-npm-maven:latest

build:
  stage: build
  script:
    - mvn clean install -DskipTests
  only:
    - master

  artifacts:
    paths:
      - ./target/sparker-0.0.1-SNAPSHOT.jar
