image: npm:14.10.1-stretch

build:
  stage: build
  before_script:
    - npm install -g create-react-app
  script:
    - mvn clean install
  only:
    - master

  artifacts:
    paths:
      - ./target/sparker-0.0.1-SNAPSHOT.jar
