image: cschockaert/docker-npm-maven:latest

build:
  stage: build
  before_script:
    - npm install -g npx
  script:
    - mvn clean install
  only:
    - master

  artifacts:
    paths:
      - ./target/sparker-0.0.1-SNAPSHOT.jar
