image: node:14.10.1-alpine

build:
  stage: build
  before_script:
    - apk add maven
    - apk add openjdk11 
    - npm install -g create-react-app
  script:
    - mvn clean install
  only:
    - master

  artifacts:
    paths:
      - ./target/sparker-0.0.1-SNAPSHOT.jar
